### ISSUE TITLE
README's sole link is broken

### ISSUE THREAD

**Issue by jab** [GoogleWebComponents/google-recaptcha#10]
All the README says is "See the [component page](http://googlewebcomponents.github.io/google-recaptcha) for more information", but that link is broken.

**Comment by jab** [comment]
In the meantime, http://cbalit.github.io/re-captcha/components/re-captcha/

**Comment by jab** [comment]
Hey @addyosmani / @cbalit, as long as we're in here, could you please confirm status of this element / whether Google is providing first-class support / maybe clarify history quickly? (Possibly in the README which is currently very sparse?)

I assume this is Google-supported, since it looks like you're triaging, but on the other hand:

- This element is conspicuously missing from https://elements.polymer-project.org/browse?package=google-web-components even though other elements under https://github.com/GoogleWebComponents are there.
- The coding style here doesn't match the style of other GoogleWebComponents elements.
- So far @cbalit is the only one I've seen providing PR review and https://github.com/cbalit doesn't show any affiliation with Google. Nothing wrong with that (of course!) but would be awesome to clarify relationships + more clearly set support expectations for users.

Thanks in advance.

**Comment by cbalit** [comment]
@jab, I can only give you my point of view.  Re-captcha element was first made for an internal usage. This is why you can find that it doesn't respect Google Code conventions. For the google-recaptcha element @addyosmani will be better then me to answer your questions. If i answer on PR it is just because i feel involve in the evolution of this project. And off course some new features could be add in re-captcha element.

**Comment by jab** [comment]
Thanks for explaining @cbalit, and much appreciate your PR review again! Look forward to hearing more from the Google side.

**Comment by addyosmani** [comment]
Hey folks. Thanks for starting this thread. As mentioned, this element is a forked version of the one from @cbalit. We originally wanted to do an official version of it but haven't quite had the bandwidth to. My two cents: we can either drop this repo and encourage the upstream one from @cbalit as the canonical one folks should use or alternatively we can start work on a PR that does bring this in line with the Google code-style conventions and invite @cbalit to collaborate on that if he's interested. I'm pretty chill either way and don't want to take away from the original project that was forked if there's a desire to make that the main one.

**Comment by jab** [comment]
Thanks for the info @addyosmani. I think there's value in Google offering an official version, both for users and for Google. And if the only thing blocking that now is code style, I think if an issue is created for that, you could very well see a community-contributed PR for that in short order. Just a matter of whether Google can commit bandwidth for reviewing and maintaining. Looks like other users as well as myself assumed it could, since this repo is under the https://github.com/GoogleWebComponents org, and so already invested in this version. So if it's all the same to you, can we make this one canonical?

**Comment by jab** [comment]
As long as it's up in the air whether this repo is being maintained, I created a PR in #13 just linking to this issue from the README, so future users have less chance of investing time into a possibly-unsupported project.

**Comment by jab** [comment]
Hey again,
Could someone at Google (in devrel or otherwise) please make a call here or ping someone who can?
Thanks and hope you don't mind my asking again. Hoping Google can keep offering this and that #12 can get reviewed while I still have bandwidth to give.
Best wishes!
/cc @robdodson (et al.)

**Comment by jab** [comment]
Hi @addyosmani, @robdodson, et al., I was happy to read @robdodson wrote this recently in another issue:
> Our plan for 2016 and beyond is to give more ownership and control back to the community. So when someone opens an issue, instead of letting it just sit there, we ask the creator to open a PR and offer to help them through the process.

and I was reminded of this issue. So just wanted to ping you again on this. Happy 2016!

**Comment by robdodson** [comment]
Hey @jab thanks for bringing this up! I'm cool with merging the PR but don't have the rights to do so on this repo. Pinged Eric and Addy over on #13 to see if we can get it merged.

**Comment by jab** [comment]
@robdodson @addyosmani Thanks, merging #13 is a great start. Now, what should happen next to determine the status of this repo? Is there a manager that can be pinged, or...?

**Comment by robdodson** [comment]
@tjsavage @addyosmani what do you think sirs? Should we assign a team member to this element or put our effort behind https://github.com/cbalit/re-captcha ?

**Comment by tjsavage** [comment]
We should clear this repo and point to @cbalit's https://github.com/cbalit/re-captcha

**Comment by jab** [comment]
Sorry to see Google decided not to support their own reCAPTCHA web component. Feel like I got burned by putting time into this repo (e.g. #12), but glad others won't in the future. @cbalit, I'd try to port my changes back over to your repo, but unfortunately too short on time for duplicated effort at the moment. Hope someone else will step up.

**Comment by tjsavage** [comment]
Hey @jab, apologies for the reversal here, I hope your work on #12 can still be valuable and upstreamed to the original repo. I think it's better to have one canonical version of this element that everyone can contribute to at https://github.com/cbalit/re-captcha vs. splitting the effort.
